SELECT A.AUTHOR_ID, AUTHOR_NAME, CATEGORY, TOTAL_SALES
FROM AUTHOR A
JOIN (
    SELECT B.BOOK_ID, AUTHOR_ID, CATEGORY, SUM(CNT*PRICE) AS TOTAL_SALES
    FROM BOOK B
    JOIN (
        SELECT BOOK_ID, SUM(SALES) AS CNT
        FROM BOOK_SALES
        WHERE SALES_DATE LIKE ('2022-01%')
        GROUP BY BOOK_ID
    ) S
        ON B.BOOK_ID = S.BOOK_ID
    GROUP BY AUTHOR_ID, CATEGORY
) T
    ON A.AUTHOR_ID = T.AUTHOR_ID
ORDER BY A.AUTHOR_ID, CATEGORY DESC;