SELECT THIRD.ID
FROM ECOLI_DATA THIRD
JOIN (
    SELECT SECOND.ID
    FROM ECOLI_DATA SECOND
    JOIN (
        SELECT ID
        FROM ECOLI_DATA
        WHERE PARENT_ID IS NULL
    ) F
        ON SECOND.PARENT_ID = F.ID
) S
    ON THIRD.PARENT_ID = S.ID
ORDER BY THIRD.ID;